{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMKXP5tqXwHLvhyzoSikIgs",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/suyash469/Suyashguptads/blob/master/caption_project.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "RCxfKpSDS4W3",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "e2010411-a267-4db0-9bd0-3bc137b76163"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Downloading captions annotations (~241 MB)...\n",
            "Done.\n",
            "Extracting...\n",
            "Done.\n",
            "Loaded 414,113 train captions and 202,654 val captions\n",
            "{'p95_len': 17, 'MAX_LEN_used': 17}\n",
            "{'vocab_size': 10000, 'val_tokens': 2528021, 'val_oov_tokens': 11728, 'val_oov_rate_percent': 0.46}\n",
            "Saved files: ['tokenizer.json', 'vocab.txt']\n"
          ]
        }
      ],
      "source": [
        "File: coco_tokenizer_suyash.py\n",
        "Author: Suyash Gupta\n",
        "Project: Image Captioning - Tokenizer & Vocabulary Planning\n",
        "Description:\n",
        "\"\"\"  This script builds a tokenizer for the MS COCO dataset.\n",
        "    It cleans captions, builds vocabulary, adds special tokens,\n",
        "    computes max caption length, and saves tokenizer artifacts.\n",
        "\n",
        "Output (as observed in Jupyter Notebook):\n",
        "------------------------------------------\n",
        "Downloading captions annotations (~241 MB)...\n",
        "Done.\n",
        "Extracting...\n",
        "Done.\n",
        "Loaded 414,113 train captions and 202,654 val captions\n",
        "{'p95_len': 17, 'MAX_LEN_used': 17}\n",
        "{'vocab_size': 10000, 'val_tokens': 2528021, 'val_oov_tokens': 11728, 'val_oov_rate_percent': 0.46}\n",
        "Saved files: ['tokenizer.json', 'vocab.txt']\n",
        "\"\"\"\n",
        "\n",
        "\n",
        "import os, json, zipfile, urllib.request, re, math\n",
        "from collections import Counter\n",
        "\n",
        "# --------------------\n",
        "# 0) Paths and settings\n",
        "# --------------------\n",
        "DATA_DIR = \"data/coco2014\"\n",
        "ANNOT_ZIP = os.path.join(DATA_DIR, \"annotations_trainval2014.zip\")\n",
        "ANNOT_URL = \"http://images.cocodataset.org/annotations/annotations_trainval2014.zip\"\n",
        "ANNOT_DIR = os.path.join(DATA_DIR, \"annotations\")\n",
        "\n",
        "# Tokenizer config (you can change these)\n",
        "VOCAB_SIZE = 10000         # try 15000 if OOV rate is high\n",
        "RESERVED = {\"<pad>\": 0, \"<unk>\": 1, \"<start>\": 2, \"<end>\": 3}\n",
        "\n",
        "os.makedirs(DATA_DIR, exist_ok=True)\n",
        "\n",
        "# --------------------\n",
        "# 1) Get captions (no images needed)\n",
        "# --------------------\n",
        "if not os.path.exists(ANNOT_ZIP):\n",
        "    print(\"Downloading captions annotations (~241 MB)...\")\n",
        "    urllib.request.urlretrieve(ANNOT_URL, ANNOT_ZIP)\n",
        "    print(\"Done.\")\n",
        "\n",
        "if not os.path.exists(ANNOT_DIR):\n",
        "    print(\"Extracting...\")\n",
        "    with zipfile.ZipFile(ANNOT_ZIP, \"r\") as z:\n",
        "        z.extractall(DATA_DIR)\n",
        "    print(\"Done.\")\n",
        "\n",
        "train_json = os.path.join(ANNOT_DIR, \"captions_train2014.json\")\n",
        "val_json   = os.path.join(ANNOT_DIR, \"captions_val2014.json\")\n",
        "\n",
        "def load_captions(json_path):\n",
        "    with open(json_path, \"r\", encoding=\"utf-8\") as f:\n",
        "        data = json.load(f)\n",
        "    return [ann[\"caption\"] for ann in data[\"annotations\"]]\n",
        "\n",
        "train_raw = load_captions(train_json)\n",
        "val_raw   = load_captions(val_json)\n",
        "\n",
        "print(f\"Loaded {len(train_raw):,} train captions and {len(val_raw):,} val captions\")\n",
        "\n",
        "# --------------------\n",
        "# 2) Clean text and add special tokens\n",
        "# --------------------\n",
        "punct_regex = re.compile(r\"[^a-z0-9\\s]\")   # keep lowercase letters, digits, spaces\n",
        "space_regex = re.compile(r\"\\s+\")\n",
        "\n",
        "def clean_text(s: str) -> str:\n",
        "    s = s.lower().strip()\n",
        "    s = punct_regex.sub(\" \", s)\n",
        "    s = space_regex.sub(\" \", s).strip()\n",
        "    return s\n",
        "\n",
        "def add_tokens(s: str) -> str:\n",
        "    return f\"<start> {s} <end>\"\n",
        "\n",
        "train_clean = [add_tokens(clean_text(c)) for c in train_raw]\n",
        "val_clean   = [add_tokens(clean_text(c)) for c in val_raw]\n",
        "\n",
        "# --------------------\n",
        "# 3) Decide max caption length (use 95th percentile)\n",
        "# --------------------\n",
        "lengths = [len(s.split()) for s in train_clean]\n",
        "\n",
        "def pctl(values, p=0.95):\n",
        "    xs = sorted(values)\n",
        "    if not xs: return 0\n",
        "    k = (len(xs) - 1) * p\n",
        "    f, c = math.floor(k), math.ceil(k)\n",
        "    if f == c: return xs[int(k)]\n",
        "    return int(round(xs[f] * (c - k) + xs[c] * (k - f)))\n",
        "\n",
        "p95 = pctl(lengths, 0.95)\n",
        "MAX_LEN = max(15, min(30, p95))  # clamp to a reasonable range\n",
        "print({\"p95_len\": p95, \"MAX_LEN_used\": MAX_LEN})\n",
        "\n",
        "# --------------------\n",
        "# 4) Build vocabulary (top-K, exclude reserved tokens)\n",
        "# --------------------\n",
        "counter = Counter()\n",
        "for cap in train_clean:\n",
        "    for tok in cap.split():\n",
        "        if tok not in RESERVED:\n",
        "            counter[tok] += 1\n",
        "\n",
        "kept = [w for w, _ in counter.most_common(VOCAB_SIZE - len(RESERVED))]\n",
        "\n",
        "word_index = dict(RESERVED)  # token -> id\n",
        "idx = len(RESERVED)\n",
        "for w in kept:\n",
        "    word_index[w] = idx\n",
        "    idx += 1\n",
        "\n",
        "index_word = {i: w for w, i in word_index.items()}  # id -> token\n",
        "UNK_ID = RESERVED[\"<unk>\"]\n",
        "\n",
        "def text_to_ids(text: str):\n",
        "    return [word_index.get(tok, UNK_ID) for tok in text.split()]\n",
        "\n",
        "# --------------------\n",
        "# 5) OOV rate on validation set\n",
        "# --------------------\n",
        "val_ids = [text_to_ids(s) for s in val_clean]\n",
        "val_token_count = sum(len(x) for x in val_ids)\n",
        "val_oov_count = sum(1 for x in val_ids for t in x if t == UNK_ID)\n",
        "oov_rate = (val_oov_count / max(1, val_token_count)) * 100.0\n",
        "\n",
        "print({\n",
        "    \"vocab_size\": len(word_index),\n",
        "    \"val_tokens\": val_token_count,\n",
        "    \"val_oov_tokens\": val_oov_count,\n",
        "    \"val_oov_rate_percent\": round(oov_rate, 2)\n",
        "})\n",
        "\n",
        "# --------------------\n",
        "# 6) Save artifacts for the project\n",
        "# --------------------\n",
        "ARTI_DIR = os.path.join(DATA_DIR, \"tokenizer_artifacts\")\n",
        "os.makedirs(ARTI_DIR, exist_ok=True)\n",
        "\n",
        "# vocab.txt (index -> token, one per line)\n",
        "with open(os.path.join(ARTI_DIR, \"vocab.txt\"), \"w\", encoding=\"utf-8\") as f:\n",
        "    for i in range(len(index_word)):\n",
        "        f.write(index_word.get(i, \"<unk>\") + \"\\n\")\n",
        "\n",
        "# tokenizer.json (config + mappings)\n",
        "config = {\n",
        "    \"vocab_size\": len(word_index),\n",
        "    \"max_len\": MAX_LEN,\n",
        "    \"reserved\": RESERVED,\n",
        "    \"preprocessing\": {\n",
        "        \"lowercase\": True,\n",
        "        \"strip_punctuation\": True,\n",
        "        \"keep_digits\": True,\n",
        "        \"note\": \"Applied clean_text(); added <start>/<end> to each caption\"\n",
        "    },\n",
        "    \"stats\": {\n",
        "        \"train_captions\": len(train_clean),\n",
        "        \"val_captions\": len(val_clean),\n",
        "        \"p95_len\": p95,\n",
        "        \"val_oov_rate_percent\": round(oov_rate, 2)\n",
        "    },\n",
        "    \"word_index\": word_index,  # token -> id\n",
        "    \"index_word_head\": {str(i): index_word[i] for i in range(min(20, len(index_word)))}  # preview\n",
        "}\n",
        "with open(os.path.join(ARTI_DIR, \"tokenizer.json\"), \"w\", encoding=\"utf-8\") as f:\n",
        "    json.dump(config, f, ensure_ascii=False, indent=2)\n",
        "\n",
        "print(\"Saved files:\", os.listdir(ARTI_DIR))"
      ]
    }
  ]
}